const data = {
  products: [
    {
      name: 'لپ تاپ اول',
      slug: 'laptop-one',
      category: 'Laptop',
      image: '/images/laptop.jpg',
      isFeatured: true,
      featuredImage: '/images/laptop.jpg',
      price: 70,
      brand: 'Lenovo',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular laptop',
    },
    {
      name: 'لپ تاپ دوم',
      slug: 'laptop-two',
      category: 'Laptop',
      image: '/images/laptop.jpg',
      isFeatured: true,
      featuredImage: '/images/laptop.jpg',
      price: 80,
      brand: 'Asus',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular laptop',
    },
    {
      name: 'موبایل اول',
      slug: 'mobile-one',
      category: 'Mobile',
      image: '/images/mobile.png',
      price: 90,
      brand: 'Xiaomi',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular mobile',
    },
    {
      name: 'موبایل دوم',
      slug: 'mobile-two',
      category: 'Mobile',
      image: '/images/mobile.png',
      price: 90,
      brand: 'Xiaomi',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular mobile',
    },
    {
      name: 'کنسول اول',
      slug: 'console-one',
      category: 'Console',
      image: '/images/ps5.webp',
      price: 95,
      brand: 'PS5',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Game Console',
    },
    {
      name: 'کنسول دوم',
      slug: 'console-two',
      category: 'Console',
      image: '/images/ps5.webp',
      price: 95,
      brand: 'PS5',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Game Console',
    },
  ],
};
export default data;
